 %Start of checkboard
    function winner=checkboard(playermark,commark)
        if ((playermark(1,1)==1)&&(playermark(1,2)==1)&&...
            (playermark(1,3)==1))||...
           ((playermark(2,1)==1)&&(playermark(2,2)==1)&&...
            (playermark(2,3)==1))||...
           ((playermark(3,1)==1)&&(playermark(3,2)==1)&&...
            (playermark(3,3)==1))||...
           ((playermark(1,1)==1)&&(playermark(2,1)==1)&&...
            (playermark(3,1)==1))||...
           ((playermark(1,2)==1)&&(playermark(2,2)==1)&&...
            (playermark(3,2)==1))||...
           ((playermark(1,3)==1)&&(playermark(2,3)==1)&&...
            (playermark(3,3)==1))||...
           ((playermark(1,1)==1)&&(playermark(2,2)==1)&&...
            (playermark(3,3)==1))||...
           ((playermark(3,1)==1)&&(playermark(2,2)==1)&&...
            (playermark(1,3)==1))
            winner='p';
        elseif ((commark(1,1)==1)&&(commark(1,2)==1)&&...
                (commark(1,3)==1))||...
               ((commark(2,1)==1)&&(commark(2,2)==1)&&...
                (commark(2,3)==1))||...
               ((commark(3,1)==1)&&(commark(3,2)==1)&&...
                (commark(3,3)==1))||...
               ((commark(1,1)==1)&&(commark(2,1)==1)&&...
                (commark(3,1)==1))||...
               ((commark(1,2)==1)&&(commark(2,2)==1)&&...
                (commark(3,2)==1))||...
               ((commark(1,3)==1)&&(commark(2,3)==1)&&...
                (commark(3,3)==1))||...
               ((commark(1,1)==1)&&(commark(2,2)==1)&&...
                (commark(3,3)==1))||...
               ((commark(3,1)==1)&&(commark(2,2)==1)&&...
                (commark(1,3)==1))
            winner='c';
        elseif sum(sum(playermark))+sum(sum(commark))==9
            winner='d';
        else
            winner=[];
        end
    end
    %End of checkboard
