 function drawcross(row,col)
        line([row-0.3 row+0.3],[col-0.3 col+0.3],...
             'LineWidth',5,...
             'Color',[0 0 0])
        line([row-0.3 row+0.3],[col+0.3 col-0.3],...
             'LineWidth',5,...
             'Color',[0 0 0]);
    end
    %End of drawcross
